### ISSUE TITLE
Is there  an example markdown file?

### ISSUE THREAD

**Issue by lidaling** [steel1990/markdown-impress#2]
Is there  an example markdown file?
I have try write one file .The dist html seems in wrong format.
I need help.

**Comment by steel1990** [comment]
The readme is a sample.
http://binbinliao.com/markdown-impress/

**Comment by lidaling** [comment]
Is it OK?

```
# Title

sub title

-----
<!-- x=0 y=0 rotate=0 -->

＃Second page

line aaa

-----
<!-- x=500 y=0 rotate=0 -->

＃Third page

line aaa

-----
<!-- x=1500 y=0 rotate=0 -->

#end
```

**Comment by steel1990** [comment]
please use 6 '-' to separate pages!

like "------"

**Comment by steel1990** [comment]
https://raw.githubusercontent.com/steel1990/markdown-impress/master/README.md is my example
